name: Python Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  run-python-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Working Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Disable Debug Mode
        run: set +x

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Upgrade pip
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip

      - name: Install Dependencies
        run: |
          source .venv/bin/activate
          pip install requests testrail google-api-python-client

      - name: Update System Packages
        run: sudo apt-get update

      - name: Install Zip
        run: sudo apt-get install -y zip

      - name: Run Python Script
        run: |
          source .venv/bin/activate
          python automation-playwright/generate_result.py
          
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3
        with:
          target_branch: gh-pages
          folder: result
          publish_dir: result

      - name: Deploy Results to GitHub Pages
        uses: upload-pages-artifact@v2
        with:
          path: result/multiplication_tables.txt

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2