# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Playwright Tests
on:
  push:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
       cat /etc/os-release
       sudo apt-get update
       sudo apt-get -y dist-upgrade
       curl -O https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz
       tar -xf Python-3.12.0.tgz
       cd Python-3.12.0
       ./configure --enable-optimizations
       make -j$(nproc)
       sudo make altinstall
       sudo apt-get install --no-install-recommends --no-install-suggests -y curl libpq-dev  build-essential python3.12 python3.12-dev python3.12-venv
       sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1
       python -V
       python3 -m venv .venv
       source .venv/bin/activate
