name: Python 3.12 Setup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies for Python build
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libssl-dev \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libreadline-dev \
          libsqlite3-dev \
          libgdbm-dev \
          libdb5.3-dev \
          libbz2-dev \
          libexpat1-dev \
          liblzma-dev \
          tk-dev \
          libffi-dev \
          curl \
          libpq-dev

    - name: Download Python 3.12 source code
      run: |
        curl -O https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz
        tar -xf Python-3.12.0.tgz

    - name: Build and install Python 3.12
      run: |
        cd Python-3.12.0
        ./configure --enable-optimizations
        make -j$(nproc)
        sudo make altinstall

    - name: Verify Python version
      run: python3.12 --version
