name: Python 3.12 Setup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      run: |
        sudo apt-get update
        sudo apt-get install software-properties-common -y
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install --no-install-recommends --no-install-suggests -y \
          curl \
          libpq-dev \
          build-essential \
          python3.12 \
          python3.12-dev \
          python3.12-venv

    - name: Check Python version
      run: python3.12 --version
