name: Run Python Tests in Parallel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Code
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

          
      - name: Run Linting
        run: |
          echo "Lint check"

  unit-tests:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          
      - name: Run Unit Tests
        run: |
          echo "Running Unit Test cases"

  integration-tests:
    runs-on: ubuntu-latest
    name: Run Integration Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          
      - name: Run Integration Tests
        run: |
          echo "Running Test cases"
          
  deploy:
    runs-on: ubuntu-latest
    name: Deploy (Runs after Tests)
    needs: [lint, unit-tests, integration-tests]  # Deploy only if tests pass
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          

      - name: Deploy to Production
        run: |
          echo "Deploying to production..."

